# Generated by Django 5.1.4 on 2024-12-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app9', '0004_tag_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(default=1, related_name='news', to='app9.tag'),
        ),
    ]
